services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\CommandsChainBundle\:
    resource: '../../'

  App\CommandsChainBundle\CommandsManager:
    arguments:
      $chainedServices: !tagged_iterator app.chained.console

  App\CommandsChainBundle\EvenSubscriber\CommandEventSubscriber:
    arguments:
      $chainedServices: !tagged_iterator app.chained.console